services:
  mysql:
    image: mysql:8.0.36
    env_file: ./env/db.env
    volumes:
      - ./db-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    env_file: ./env/app.env
    ports:
      - "8080:8080"

volumes:
  db-data: